sudo: false
language: node_js
node_js:
- node
script:
- npm run lint
- npm run check
- npm run browsertest
- npm run coverage
dist: trusty
sudo: false
os: linux
addons:
  apt:
    packages:
      - xvfb
before_script:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
env:
  matrix:
    secure: pu+Ia+KRh9CdjXwCYNQ2/2uXoUoZ6k8uMNIgJ39+Qr5FSrhvlzuoHjNjuXrm/gRz4pO7vsXr7Fmr68X9oeMoDm8L8tb7dEIuoL7ti1dlVUt/PvdFcSadyIt/+xCpMjv6oA3rKulQfJbXQSahwciqWCt1zhXVXn6PLRFS2hdh/IeZWLjDrzLHDK0Qk/+PUfe5Wk6S9m8h5vt3RiVCCpAuJJz6UuOCfvrYegb0DhvxuIuDtKA5uC9LOkFsXYSX1RZoVStxikAZaPYrYN1R7FK8PlC/4+TiCvD4NVhcqPBL2CyLtCV6S12TMB2O26b8ROYATlSEB1O7snJf+BB3NJWrTAAqWWW6KveqZa1THJwK5gXj7pkSkBIVp6A2I0zb/vlnNiWVAleTgT8EVtTyGbtlFk8BQjIL+ou7ucTNhi2GGP7kyPxrDiLTGzQVb0wW9MaQDYtkFp1Ji2ijF6/3B09fwFG1ShBB4Tqokxr+eRB53h8UXl0pfQyIduIHNg/ucqD242uGoP8fqt+PFHTcFexLM2/6W8NS/fIqXnDkdy4WZsPHT45Dz1iPEVKQ6qJw/vmSrz1qCGqga22ShecuLhsJOYs4LrH1Hi0/2tCmZ36T2G77CviI+tKjzp307X52tEUmRbPcqGwoR58/6bM7ClQaUeE2J3Dm7DxhOr4bcT6TGgA=

before_deploy:
  - zip -q -r latest *
  - mkdir -p deploy_code_upload
  - "mv latest.zip deploy_code_upload/$TRAVIS_COMMIT.zip"

deploy:
  # Staging continuous deployment
  - provider: s3
    access_key_id: &access_key_id_staging
      secure: "SGNJXm3l+gaXvUn/jQYDEZ1zILYF/KwsMpbXBYDXHfw+iRdaOkLvBEgPra0fS2ighacGaodu49rwCq5tfdEqDnI02zgsq/iGgJDDUL+SnFOcHchAqqfuFNVUHjO6y83IysYZza2bYpakVgoQ9d9r8hIHBXzcd30dOPgm3pUETthChQWSuYavG7IqVbxhQezaNfVVZ3zbMpOD9491Qh9y0iQ4UrYq0fhiV8tCquQqo5TIQwleBIl+Jad2DPtEchHgf/PiNey3L5Syhpxx2d1oLo8w+2bREPWoDOM+UyQbOaHp0FfaHtKjuNfbW8c31OPX3KGfV/79tRhVkxVI5uG8dMqMUL31ME8zLPAeqdFr6x+vcA63iCTnY9DLeLzL9ManejHr7m8ZwZcQTN21yL7gQvgtL4rsAXViy4gHGBPLiq6cZmbwh1LLEh03Qa+KdTEVTucpxT0hEYvzHjpaH8nsnV9RrjnV8/E30o9zfDxB9gvUZ3pRC0ap1khIps2DeF2T+irhNrQ8qDVuw120MZsnlLD+DDHkvsvMMtvecpr7+XQfcFn2Jc/dxrwCUwKMwcaizJbMUX7J5OaeF8I7yASFgOHq20X5rMwR9uUELfz5PlMcUbPsRPf1gbxpGqb6xSai4YEHgJp1B/tudBLpecbVyhLS0HdyspAX/GDeMvDbDv4="
    secret_access_key: &secret_access_key_staging
      secure: "xYASkRYEFQch4esVEpSlMPctjgUQF0BQeTg9+Vu2mRaHHZD9UQVzJ6LAomVKBNjSJ0L735nfNBb5z8oSkptKiEtAY6Lo5IRFuV5dr3iWyDPS2Zp+93uScj+FCAkEnWtkCS8nn7xFnf503m6ReFnWDlvuQApbGZYvvIj9/RglMfMBvYNFJG3G/Ow4eNIbj7+4z+xySIZ7TAAsqPqPidQ2jGyUPUNGi/E9kJR+KdWxwawMcRQIs0OwNjmIOsG/YZpgQ2hkYkQchUjok8s88M/+1IZYP2/WB2EjOPUcz7OXS9hAaBHke5mpCsX+JjQLtgC9IXxTIN4do3o4Zeni1YfgL2TLNHFkbQSXBkNFBWyPaWGoLk2CdjmiHuKVM5EOWQbqC/D9kvxMw3g/fDX0iYytGLBUIcR8sg47UTRLwZQa0gfhS6Ao65S3jo2Zfgkmc7mfkUwfFCfXKk8S9I/Tse1UiyGb6CMKB2RRQvRcLa4VSUShwzMI5Qo1Uo29Ml0wWcKMLUmKgLGyIARm1rPsPyg6j4b/0p1hOZeLQP4hQHDe5qEK7yebqMoiG2MuLeOJsZjmoOL/oQq27o+KIk380k1fI5+Qfd78yKvVsCFhSTt7+K+8kCdtelkhGy/GGyFJxxEZdZcvd8j2n0zKAr25T7QkHJOpC4BpmzyTz09mP++6BQw="
    local_dir: deploy_code_upload
    skip_cleanup: true
    on: &deploy_on_staging
      branch: staging
    bucket: &s3_bucket_staging
      secure: "soPxr/H5fNiDNa4hppQOXdNG6qjPaw023MyQ55/jgYWhd5SoJ0D5azvF9Q5+JQMOT/dsofGQDKLtI7nEA9jBUVSyP7V+gx87ZcsoY7bDmzEaq3NY2xzRX0g30oZ7BHpgiknBL3OpqtyXgywVcpm80COb4w3f2v4kVvCm10b8cSwE1J/JLqcGSx70npTYMQE/g93exME5652vfFmDwluBc1qcoec6inceE/EbyXZpozqoiof08vJc+jLSlRIB2V2ylPJ8s9OGaYBe0YbpPsB281R2cRMwwjbxqP187z3FQIUvsVKx/K9HHeg13U+H8pGyawsUaIJTPRLKOypxcTNavopCpOSDAwR7nhnee1Xfc3t8znAtK+5THqMMjliBPTHUVenUDdGjSM8nyqaRdGD4PU4IeYXSkKyPqvh0S/5Dxi6VMkdNLlk2mVRVGGHkCbXTZjb8q2DRb+R4UPimfVaw6F0IIIXcHHp2JrbJ9tsedvubWGEH6P9wwxquw4sm3dsLIv8OrrCm9SHpaFkSUklXN62IIxGKmISe1O+DkFKFXQUs3LcIwJ02wcjjPJ9pf38KxAGpe+3yqiNGgmgN0XWKg3WwCx+fIDqTBweNplhMTMrLte+E5lz5hTbnFo9mFVUUMRRDMuH4gaCO2ZgDH4XCZYXDnju+gd/KB/SXZKIroX0="
    region: us-west-2
  - provider: codedeploy
    access_key_id: *access_key_id_staging
    secret_access_key: *secret_access_key_staging
    bucket: *s3_bucket_staging
    region: us-west-2
    key: "$TRAVIS_COMMIT.zip"
    bundle_type: zip
    application: &application_staging
      secure: "szhdBMyKVqnUl6PG3inA9APL1Fgeck8RcGYwhK1WlkmkdtMefAMpxVrC1hfJFM7uMIyZuQv58T8QDs+FtAvtBIaa7EUHgaVtjsjiRkJqZbnbRSTY2znfHjsmhXL20cMsvudLxKO1XFk798AgmQAaIQbB/NcaVWqI7M2C27p8f+JMtaKVKW0sX9i9MdaRM1UfynArcrfoVCNMGmjJb1hAy+a9QPfGcjVX26KEhEksYeiFxTvuk4LsWGs9gXxv9JTqENFkoXmCq/PVFH0x/+wY1ACNQTAm/bNzeXBqaqJEJ5NYscSrX9IogsjYrSXxe0h3d8QheYvejdnpyIWLI92sPmMAJtoTBAWI2NGymnywNYej153M5PJQkeMKbIaus+5fUKcrG7uHzSw/WDk5a6Nuo8XfsCpXxsZCZtGFmzQZUOkylvA1FK+mWp4gAoLXor2/hTx0jdJa9EQ5o2Nis4un9Rq+TCB9ymFxG/5OvHx7hoKu2sw9tLniXIMs19pyWl82+LXb4EspWV9v0ZuZHnfK+1Xmmx8QXfV0x1TN3huyQ5d0sTJw35muPNdXQFmCBBh3oEGK+0wrIjNtwP5f0Koqd/9D6DeFGltVMKOVUww4j8xukF3UNae/RpasKLXb5E1QoOldw5XiU5dSnwGIkULAk/8pG4sRabuYZCYGUOQYtGQ="
    deployment_group: *application_staging
    on: *deploy_on_staging
  # Prod continuous deployment
  - provider: s3
    access_key_id: &access_key_id_production
      secure: "LWurtU7hC+bed4WB7RLQzF2gfkIW1YA+CHgiDnX1cyMB0uPEbH5J86wAsWmm6xz82tR7mZcpoLPOgMd5+PLSyXwMfYUhl/w0W7oIgduZetUT28Zw9Wr2Iy48SOw3xZZaTmxmvCMYxFZAS48C+yoP4QwJahwXddFPcHsM3BlbKXGplksVtZiwPAVmjkgQ2p3W6GuaOzMDSbGHVYwJBUw+mlCHO8rZdEN/7NRimS6IJ8w3xkMMHN87O/7f5o3d8k80IqKNFO5ub8dw0bdbl+lnyI7C61mrWkQJFOzB2hZETjYhaQE9cioZYFp8CSU7qKtdRO+uFVWwutsfZ3zj0YyBt2Dp9kyDnqCYbK8PCVfcsb//WAX7iGN1w8Upv3OT6iorpBE/0PSZhYgV+lYi0HXW6kznbQROnCqQSGKj0s4fXAdheGfpvpijkiG5rXZd3gB8oAqgsG5BCKppQVTdtytR+/tr/2YJk1An6oU6lB/G+EoqYRUWTPwBxT56WLUoWaxVUXMctapKgdfhgMMBk1S82YVMrbg9XXqApVALHCc+SEULttxMhqcSnRnICQBPJfyXRStHu8QB1ICZE2FGgb0a3E1f34iepREnoEmNc0fynz9ED2KVQN/HxKzuXa1n8cQipZQOwOm0cuVu4G1UMZuRy6C4rvVr18ZR9jhO5huKBL0="
    secret_access_key: &secret_access_key_production
      secure: "zr3MpjgkrcxubfeEaUToHZvUHwVg4dRf9d9echXQLZl/qVb3srmo07SFlEzpPCCofcvIW0A8B3d3+9zN3eRTiUZCfWyL9MNpwGvYhjb9TfuPJKfYhy/201yTlNJjxjrTZ7i1nL/k+aqpcRR5yUXoF8hA/KCx4anFklGuOn42oWoA0R5EBf4tDhV6/Hzz8UR155zAiUpt5CWYqEgYp3QoBHfmDTqyHm8QRaaMxkR66OXoa5e3wuPhGZE78/X7SlHM8mwVKNejNrwoF2Szw0Viv2mRb+bj0UyYmA88efQoo5A6GQt7io0U+oeHFShKEUJVWyBvg72S6jXklAH/nGPdFC1CLEP9Hb9S4oxY70r2DwS8sHlccioycVTear1YQ7iuAiU52yorin3XiJv/tI041ZR0/ZEH7Q5FBbkph9EeXJs5FdCL++bj9a5Pf19qltWoKvEBG7Gg8pRIuby+U7Rt4hHy767wDBMKA0eALqogNcFluRlr/E1rPegdPmvL5FsvWPwm9HYVMi8PM79CTKnpYkZBAYoI+lRTTL4u1QonoVSu8dQvU1X1TYmRAak5GyIAIzllW9l3H++zOY0piNBilqOUNfX2AnCHbHR9yNMvkiGxMwQUeZ9F+s6K031gx1GBT486gnZ0Jltzdrl/qXk5R4s1RMGX+HaFTSeyeySkUcg="
    local_dir: deploy_code_upload
    skip_cleanup: true
    on: &deploy_on_production
      branch: master
    bucket: &s3_bucket_production
      secure:  "Rpue8M7F8mHruJQhlBpAL9DMOQqd/O71XUXTVp5jGBvvv+pfM0to4eI6XpGNekRiSid2tiOY8+dG1OPAe4GFjQ/8B+wGnnIq37KzyQZUP4fGkfixaLmv6Fs5JS97Fs19DgWSt3P3Ov+k379Htd8+b1HkaDfOTBm9DMWbwbTfnrftS0q64kxP5pN/Xin+7x055zwa/YOrI182Ts70X2YQ56NMLFjAaXpvIln2VFYBOuEsXBVmwG1N+n2eZrvBCNfk5D8jgoffcHGVXhY1TvR9EnCzaPs9uZ+5YrI/H1NIjXXZ67Jn99dLY1XE+I0JsE2PjnbcLvhwPhD67RLu8orXir1cLeY2LZSW37j3tfjkoaS1dnvNVFVOL+l31teigbe8ZgxqNBQxyiQY/7Zr3Uu+0OtgIUQYv1PprJIcNfFFgukp6J5LgGrWbHH4AHyCQh13veWT4t3gRMWXWxFiPxmnR+1WkiosYEckAyN6wxOTHrMiFIFhfdFOBkhtQys/sTylUU1iCjMt0E5MKO3XVOEkfe5QG0UiZJYT7tbH1xByPlSWgFQ45dig+d+lBavH6HnhbwqrDltW/zSpYT+t1a+cG1caCXRk/4Po46HIXMkuPjxcFjujTSWKpUbcgzZcdtZ2SyCAYe7MNlgBNvkIjDFaZrURY28IGffG28XgA1p5MhE="
    region: us-west-2
  - provider: codedeploy
    access_key_id: *access_key_id_production
    secret_access_key: *secret_access_key_production
    bucket: *s3_bucket_production
    region: us-west-2
    key: "$TRAVIS_COMMIT.zip"
    bundle_type: zip
    application: &application_production
      secure: "YXWlfHjYqq/TJenXSCs0p5CHjqwRQN9okmbalGGylyuApwWHAGtCRQzt5mEPrZCAyM5iq0HabQT7hD+gxsSDzJuvxlumJGRLEtG2IYi+IwUgwdsXm4LsMco5JXC79DA++nKnac6QWbpbpuBbKJDnlCUJ4nE2ZLHTfM+gY3xzwdfbZpVDcXmtg1HE0NrqjRmGluV17iWSsq1swaPpzITE5xEa7qYgbX5Od0rvJT2V+CSyM68VQGNdVqB+nfh+ZalbLDLCzPXEF9OzZxMsxo4+zi31prtIRoS2mFdMTIlmy9fBm8QG2nSOGGHQKOMVSKYKfP4Je33aSGW5ltERNKsd9ibVBdZY1ovHY/rx8w4t+po83W4gkMC7OTFKZ0boK/ZHKoW0Km9fOK+p7PMCAoMqioAROzhLm18HOHrSDRgt2PDQICf2QapZoLjPbABzomAoR7MU+7rlwfkn6Htz8JVe5VE9l+MXfChN/5NyCvgmyu0u76uSBGguNKlmjEWI/TXTwLcY/iT7Mb1hIdFzLrbLfG2CmNFbrP4GEraws+hazotdFJ1y4Rx0h3U1g2DOc/NRq/EuXNdxXR8UPY7xNJ+LupB64uqdG3J4tb7rXbt/pPxi7vJ9zBLt6p0z0Xn+VQ1+7D0BPdMrFMwU5u8KuZE9bOwXezGVM2P/c04vNayAOS0="
    deployment_group: *application_production
    on: *deploy_on_production
