sudo: false
language: node_js
node_js:
- node
script:
- npm run lint
- npm run check
- npm run browsertest
- npm run coverage
dist: trusty
sudo: false
os: linux
addons:
  apt:
    packages:
      - xvfb
before_script:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
env:
  global:
    - secure: "qWnZ3qqPC7dNSO4/McwAthMjOQTzRNVIVhvDyf/b9w6YEutGeSk1TqAr95F/RkbSZp/1VDwYLqb8iqw5V6YboBhQ+aDcii15Jz38CWYPqryxokO3pxWqh/fuXKGsZWqv2Buh9kWh7WbSRxYb5dfAGWTbUa1y9EjneU8aCi6ggkSLMjVz/qk0ZOKAc8llwqfLAzZwWoM+hGv9ooaiOcgmdUa8QV7ciEGA6RTyivML9gGJ/rxYjI7iURQ4LguNxtNaoQ7Dj+XE8tJX5E1zCjYmjwLsZD3iAUEMJhq6MofEDKQbwIkFdln2Ngl++yhBnUCQTHU4dPvUEFl5fiTSdS83ISojUXKnJG4jF5HUICKjk6UO/yJgvQarQPRfxOm0DUa5B6Bha3C99wYDi6/a5gHbkBU6V7OU8l2PPWh/jtmSkdFnQp6eJyZdALB+0v+rG2Jjm08mxdhfuNh/gyK2S3wxwQivMFP4uSL2qfOltws2J/GyJf8lnKgZrPdceHibIeOTuPG0/PmCoTf3BhkpHW3sR2MtSRSEMkqKgAUSdEIfms2uUpGAbX864bsvYXheJ4p34tAk05vYijWOSEETLPMA5Ne+PtjrWXxyfW5NpJvPtM5YVAptjVftXN3JcsZrhtPnRWeEHGuDwZAwxuvJ8ZU1HtjJHppqcpnL9wvSGziUAow="
    - secure: "nB2RKmyYBil3Q5K6l69hx+ZFawW8uYS2c0uc3qYtA9tsJkAPY+nAlNci2apjUbL/3zAaxyBQjzDhSonAKyNdN1pqTMlYqoIa52jjCrPu1CTKrAimqMDtSaEyOOcMK8mtCfph/cvTCMu70cCiNIuGEoU2nGUf/CebuYBm9xGL2WIpKD/O2LdRdAdpqi0zVUgStFpnuRDDxLzvt76zWHEeagcx7vPuCLGfHMocn07f3mdT/OhlxdDPwyrJB7/3rxxiB/HyB2Jnc7uMmAbGHiLKUNQdjRLkvAzIusuNZKrBlHVf9DqbrWaPdZm3FmHTo4Mu1n724phqZBYeHAvGy8rhkkOgS4x9wALNar0UlEmhetVYd5rP+/K1Pzif4jU2zYshGCoYfHOyT4GHxII7Iq6b7ZBad28ZvDyBMbbnbAoIf70HUHyyPhQtGY0eT1LI3jW/+GhkZXCY6rG3CuG7Tioz3JzY5s4F2sVO1YxkHZ3FUqNZjbWfVgeRQ/1amvPn/u5G4R897OxdPhQhF0tBfdwK7yxvsafBBjslMe9NaFpL10zCeqGJ7cGxJ7+kdgi13zofswjwngUBEZ/JYapXRzLs6RtdAIAzh6K0rVv2PP2da/DqTVFa/+TPzb88uG7kCuNZSQgSuF8/vuo17Bb+7CS1bfrRbd7xnvV1P9+xFjSs4NI="
    - secure: "KsjSldBr9pNW+YHu9xuTA0nVqf90osMtsCXYNiwtwSE0efipx06rgpE3uyxkdSMabmQiAFpDCXtFI9/reUJSIsZCt1qQr9NHOB/bEfJi28LyHwR0evmvg3tLsu6dwgBtk5fSqM2gUHO+941+cHdxpn1+G5MCHdvUaTyUf910mbUk8XyySfewo33kBb7k9J7TVCNLbHUYuUwYNs/0a3ar8cuY2iz1BWYaAZ7KBn0E9MtBCttUhoquGGM8wpPD+82g2+tC7huWzGloibEU4OwhW/FzRMttVnvQhAtwn/DIjPdqp8htfXquEYLu0jxJf73jYr3Wt4xpOQslkSA2y4P1iYZdWXU4nM14Itp7/C69tIMaWLWv6gpplga+YUmkkA/A6tszPRRw5+S1HlbdsgPLmlU9wQ0TExYxR4yWAerWRojoFU4ln49F43CpLZ8uIZaA2ioX0dN0ywYqTIQfcFg0L3PRZ8h6MIMNkg+DkXb0lseEzWkb1/RIsfvLeY2IITQIlF5ZaY1mNHVjIcXYuQVLHlshH9nHh29VQAf6nhopzBdXJ6Et7Y6vSZYbA3Vn0Q0/fF2o3dH3hbJbMYcvjtJd/Kyc1NDSfOPeO5cBqFpjI6R/4a4lKnx720WK8qUWhdogBMfK44EML24iUmUS1nGfLzLwa169rVcDs9mg2qdeNRg="
    - secure: "f1ovBtBtMwKQkdBZFH7Ft9WIjcAEF47JqhVI81EGd7m0xisU/qv74xSn9FZRGYuBMSVTZyuKfV1ZWdre415l59KLkGvr+kDuaVI9I9q3gIz2Jp8oSmjCaJaGNKnfsK5bswDV61sztiMS/qrzY5sIKSt9tuNvhRYrIzChh5OYHioS8utSW/j0bUQZ4HmD+/KV2nDTchD5eUD9rBOJ3C54t2251kB/dW3C3OiAiykKBFcIXE5SYamcn8ws+AVxYmx/lcYg13dgi0CaoXCEVXVbTWWX3mqcT7NJZLD3GlyQgNZj2CTAdb2NCZGAC0Uz3rLnXoRRwWsikFW5e7LAtc/KSg4wIdhARVF7jBMcwgDbydauy/xBQ2anc85s/8Okou6+eAXNN7mrZwxsqFhBSg4/Yb0OfPpVwlTGniK6D+hKd3bOderqFHmI3w3GC+ucRC6Nk05+wdeAhPcp8LkcvFgGbOEzgyOeJZzUpzhUDType2MK7qEnpgNrETRKETbIPTglXrccStl4kg57JFTErOs9zot6C/YaHAwB5yKMm4EQeH0t+IRV5eKJhY6kfl7ogV4V+9Tbw7n+Wkq8oQ50Apvv0TdDZHBSorCG+DVw15MhehxvzQEl6wYrEwIuJ9cXnhvlKRZS9VmHS1Jwev1U0LHvwjMrroevaJ0y/aJOyo7fRLg="

before_deploy:
  - zip -q -r latest *
  - mkdir -p deploy_code_upload
  - "mv latest.zip deploy_code_upload/$TRAVIS_COMMIT.zip"

deploy:
  - provider: s3
    access_key_id: &access_key_id_staging
      secure: "TXFkfN84fSwMiO1nJDQdsN8IsOPj8+P0QadiqFwYygpLs37iv49c9YMKhwEww1t9PXe5KZzcXHBis5XzZ9Oc5MygZw3QdaSdN2ilo3Bin4XQDgwzHpaqf/sKJEgZnTNgAi3Vzfq20PePbfx+usZA9OyJ7DsKZ/CqjKd1tr84B+pnFo7kBg+dfGi/+LzUcrG+Oq3to7ltktx091T1ci+ULlTXrjdUuWYxxBSIK43jz6c+wAodgVps04lk/w5ur5yOjTcCKlqvYMjtg58qUPD80Mm3cKf3s6/vZ6T7eU7etGsf8Q241kAD+3uWF0POf1YZ2eEeiYdsm65KhctuVHShgXG7x/K90Wajafkr5VDlGGqHqgrkSSF9ICXelt8uabj1h38hALayxX10Wu00XbmB38diVVzcrsngItYiimOVegL9kDlj6MeubC1bftEYa0H37lRU38YzHEaZ5RiSBHNCNGm/LkdHd2uirfScOn2ECv5hEJ7ZQPM9/XWPx2k18HM8dcD4wdZ+f6UdX9WGSvY2BqsAl7uTMzUv2wHfGqeon7qOgyNcumoyPUz27SonpJc1MUy6NUnAeIAJzuO4xPRPzBQ1BzDyRXEoYfjyhlGj5G8c8mZ3hBcAsCJ6yw6naU0hFBTQ1niD4GeqGoh4wxX04pnK/wGJYOhNZkbSCakwq7U="
    secret_access_key: &secret_access_key_staging
      secure: "fnLTW0P1RSVzy8YCWVrxd/HtMhUgJT9vNuuH/+gHqeCiWrrQaRUTxFbNKz+w3kO4Ynx2ugQ3hRlAhosSJVH2peO5GM0KOw2QNY15RaDI+hXMz9UAYmpdHLVAZ9+C9lMR+Xpq2PTJ/xEyPFbv2xyKAUozNmslnKF6mqHMf5IV4BxOwumQtJun3sih9H0AzSL+vBECtb9xYLF71gEPiOqOaEotphUuLi9reGS70jCBAcH4icUy0oKZndu2N+8jbp58+LSnMcaJFB6UZ55yEhYBPH4iVl7n4tQBfdLKtx7Z7NFqQWheOZ+Z036rFHckbET43e0RiSgKrzepNdSpZY3eMazn65pj5nXqxe+iI+he21jdJ9jr50gMc7C0nWmOqoAJOY/5UL7sL1fm3E2nXRYTBNGXBOa3QUEZPomnz1W2U5gm9CCIQiccOoDOLTURhLzkqA7Ic2+shmaphnpdjciwaRE8cJXxDHoxX9a49TKFfydJ9hKcnZfktmELcHoVMWFFn7K5APbu5m76kyE+5keNcqjhatMpkTSD10TGG/k8GF2IwNgjZLfrqsjXQjoRKA5+ntrGQXgAZBI+0gl613UUUITpbjoDjTJH0II47lAZtEACcvV6XHOB86sieo1UMeHXMK2J80mW0EwzZipgJDhS7d0o+i+Gtty+wlnZbtm7tDU="
    local_dir: deploy_code_upload
    skip_cleanup: true
    on: &deploy_on_staging
      branch: staging
    bucket: &s3_bucket_staging
      secure: "soPxr/H5fNiDNa4hppQOXdNG6qjPaw023MyQ55/jgYWhd5SoJ0D5azvF9Q5+JQMOT/dsofGQDKLtI7nEA9jBUVSyP7V+gx87ZcsoY7bDmzEaq3NY2xzRX0g30oZ7BHpgiknBL3OpqtyXgywVcpm80COb4w3f2v4kVvCm10b8cSwE1J/JLqcGSx70npTYMQE/g93exME5652vfFmDwluBc1qcoec6inceE/EbyXZpozqoiof08vJc+jLSlRIB2V2ylPJ8s9OGaYBe0YbpPsB281R2cRMwwjbxqP187z3FQIUvsVKx/K9HHeg13U+H8pGyawsUaIJTPRLKOypxcTNavopCpOSDAwR7nhnee1Xfc3t8znAtK+5THqMMjliBPTHUVenUDdGjSM8nyqaRdGD4PU4IeYXSkKyPqvh0S/5Dxi6VMkdNLlk2mVRVGGHkCbXTZjb8q2DRb+R4UPimfVaw6F0IIIXcHHp2JrbJ9tsedvubWGEH6P9wwxquw4sm3dsLIv8OrrCm9SHpaFkSUklXN62IIxGKmISe1O+DkFKFXQUs3LcIwJ02wcjjPJ9pf38KxAGpe+3yqiNGgmgN0XWKg3WwCx+fIDqTBweNplhMTMrLte+E5lz5hTbnFo9mFVUUMRRDMuH4gaCO2ZgDH4XCZYXDnju+gd/KB/SXZKIroX0="
    region: us-west-2
  - provider: codedeploy
    access_key_id: *access_key_id_staging
    secret_access_key: *secret_access_key_staging
    bucket: *s3_bucket_staging
    region: us-west-2
    key: "$TRAVIS_COMMIT.zip"
    bundle_type: zip
    application: &application_staging
      secure: "szhdBMyKVqnUl6PG3inA9APL1Fgeck8RcGYwhK1WlkmkdtMefAMpxVrC1hfJFM7uMIyZuQv58T8QDs+FtAvtBIaa7EUHgaVtjsjiRkJqZbnbRSTY2znfHjsmhXL20cMsvudLxKO1XFk798AgmQAaIQbB/NcaVWqI7M2C27p8f+JMtaKVKW0sX9i9MdaRM1UfynArcrfoVCNMGmjJb1hAy+a9QPfGcjVX26KEhEksYeiFxTvuk4LsWGs9gXxv9JTqENFkoXmCq/PVFH0x/+wY1ACNQTAm/bNzeXBqaqJEJ5NYscSrX9IogsjYrSXxe0h3d8QheYvejdnpyIWLI92sPmMAJtoTBAWI2NGymnywNYej153M5PJQkeMKbIaus+5fUKcrG7uHzSw/WDk5a6Nuo8XfsCpXxsZCZtGFmzQZUOkylvA1FK+mWp4gAoLXor2/hTx0jdJa9EQ5o2Nis4un9Rq+TCB9ymFxG/5OvHx7hoKu2sw9tLniXIMs19pyWl82+LXb4EspWV9v0ZuZHnfK+1Xmmx8QXfV0x1TN3huyQ5d0sTJw35muPNdXQFmCBBh3oEGK+0wrIjNtwP5f0Koqd/9D6DeFGltVMKOVUww4j8xukF3UNae/RpasKLXb5E1QoOldw5XiU5dSnwGIkULAk/8pG4sRabuYZCYGUOQYtGQ="
    deployment_group: *application_staging
    on: *deploy_on_staging
